name: Check formatting

# Controls when the action will run.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  check_formatting:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: Install formatters
        run: |
          sudo apt-get install clang-format-14 openjdk-17-jdk
          curl -sSLO https://github.com/google/google-java-format/releases/download/v1.15.0/google-java-format-1.15.0-all-deps.jar && chmod a+x google-java-format-1.15.0-all-deps.jar && sudo mv google-java-format-1.15.0-all-deps.jar /usr/bin/google-java-format-1.15.0-all-deps.jar
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.48.0/ktlint && chmod a+x ktlint && sudo mv ktlint /usr/bin/ktlint
          go install github.com/google/addlicense@latest
          go install github.com/bazelbuild/buildtools/buildifier@latest

      - name: Run format.sh and print changes
        run: |
          ./format.sh
          clang-format --version
          git diff

      - name: Check for changes
        run: "[ $(git status --porcelain | wc -l) -eq 0 ]"
